clickhouse:
  dsn: http://clickhouse:8123/?async_insert=1&wait_for_async_insert=1

insert:
  enabled: true
  listen: 0.0.0.0:9095
  id_func: name_with_sha256
  table: samples_null

select:
  table_series: series
  table_samples: samples
  autocomplete_lookback: 168h
  series_partition_ms: 86400000

prometheus:
  enabled: true
  listen: 0.0.0.0:9096
  external_url: http://127.0.0.1:9096
  page_title: Pluto
  lookback_delta: 1h
  remote_read_concurrency_limit: 10

debug:
  enabled: true
  listen: 0.0.0.0:9095
  pprof: true
  metrics: true
